### ISSUE TITLE
Slow performance with large number of guides

### ISSUE THREAD

**Issue by gorjious** [3type/GuidesPalette#1]
First off I'd like to say that this is an incredibly useful plugin that is intuitive and has the possibility to organize a lot of complexity, particularly with the use of tags which is a tremendous help to group and access.

Currently, I am working on a 10 master variable font with a height axis and 6 scripts so, across the vertical, there are a lot of guides that are helpful to place (I was previously using Global Glyph but it was becoming cluttered too quickly). 

Over the past week, I've committed to using Guides Palette to organize everything and it has done a terrific job but now I am running into a performance issue. Each master has accumulated to about 50 guides and I notice that everything, from zoom to moving nodes, has become really slow. If I delete all the guides, the issue seems to go away. 

Have you run into performance issues with a large number of guides?
Is there a limit that Guides Palette can handle?

Are there possible ways to help optimize the plugin to handle a larger number of guides?

I took a peek in the source code and noticed notes about a `HACK: in current version of Glyphs, guide.filter contains bug.` do you think this may be causing the slowdown?

**Comment by gorjious** [comment]
This may be caused by too many updates happening constantly while the palette pane is open. 

As a [bit dated post in the Glyphs forum](https://forum.glyphsapp.com/t/suppressing-glyphspalette-updates/6957) suggests maybe there is a way to suppress or deactivate updates that happen with the plugin when the palette pane is closed...that might be a way to improve overall performance, especially if there are a larger number of guides.

**Comment by gorjious** [comment]
I think I've found a solution based on the [Alignment plugin by Tim Ahrens ](https://github.com/justanotherfoundry/freemix-glyphsapp/blob/master/AlignmentPalette/Alignment.glyphsPalette/Contents/Resources/plugin.py) (line 283)

I am testing by adding this check to the beginning of `def update` and noticing a significant improvement in the performance when the pane is collapsed.

```
def update( self, sender=None ):
    # do not update in case the palette is collapsed
    if self.dialog.frame().origin.y != 0:
        return
```

In the Alignment plugin `self.dialog` is assigned slightly differently but this was causing an error.
```
# set dialog to NSView
self.dialog = self.paletteView.group.getNSView()
```
However, the original way that `self.dialog` is assigned is in your Guides plugin, seems to be working fine:
`self.dialog = self.paletteView.verticalStackView.getNSStackView()`

**Comment by mumchristmas** [comment]
> I am testing by adding this check to the beginning of `def update` and noticing a significant improvement in the performance when the pane is collapsed.

Looks great. I've tested it here and it works fine.

We don't use that many guides for now. And really didn't think about this performance issue before. Thanks for liking our idea, and thanks even more for your (bit crazy) testing and suggestions.
