### ISSUE TITLE
Ability to rename guides across all masters 

### ISSUE THREAD

**Issue by gorjious** [3type/GuidesPalette#2]
I'd like to inquire about adding the ability to rename guides directly through the plugin. 

After further progress using the plugin, I am noticing the necessity to rename guides for a better naming system/organization (and occasional spelling errors). 

The text field of the plugin makes it relatively simple to rename an individual guide which also updates the tags, however, the issue I am running to here is that the guides in all the remaining masters are not renamed and switch to being unchecked. 

To make the guide appear with the new name, I would have to go through each individual master and update the name manually.

As the tags for all masters are updated following a guide rename, it would be incredibly helpful if the new guide name would be reflected in the remaining masters. 

Would it be possible to add this automatic renaming feature?

**Comment by mumchristmas** [comment]
Thanks for the suggestion.
We have improved the behavior when renaming the guide. The old tag will now be updated for all glyphs. It's easier to use than before.

But syncing guides across masters seems to bring some new problems, we are still thinking about it.

**Comment by gorjious** [comment]
Thank you for working to improve the renaming behavior. 
I think that syncing across masters will be the missing link.

Looking forward to the update. 
Please let me know if I can help by testing.

**Comment by mumchristmas** [comment]
We still got it done. Enjoy the new version.
